### ISSUE TITLE
Create a REDME.md file

### ISSUE THREAD

**Issue by henriquecrang** [Cichinato-Ivan/Projeto-Harmony-Scents---Lembran-as#1]
Instead of having your documentation in a txt file you could create a README.md . This name is a consolidated market practice, and if you put a file with this name in the root of your project, github will automaticly show de documentation whenever someone access your project.

**Comment by Cichinato-Ivan** [comment]
Valeu Henrique vou fazer isso, obrigado

> Em vez de ter sua documentação em um arquivo txt, você pode criar um README.md. Este nome é uma prática consolidada de mercado, e se você colocar um arquivo com este nome na raiz do seu projeto, o github mostrará automaticamente a documentação sempre que alguém acessar o seu projeto.
