### ISSUE TITLE
Mover conteúdo das duas subpastas para a raiz do projeto

### ISSUE THREAD

**Issue by henriquecrang** [Cichinato-Ivan/Projeto-Harmony-Scents---Lembran-as#3]
Como falamos no Discord, a separação do readme em uma pasta separada dificulta a compreensão do projeto, e ainda evita que o GitHub faça a leitura automática do README na página principal do projeto.

**Comment by Cichinato-Ivan** [comment]
consegui realocar os diretórios

**Comment by henriquecrang** [comment]
Ficou melhor, mas ainda existe um diretório único na raiz do projeto. Sugiro mover tudo que está nele para a raiz e o remover.
